name: vistenum_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip=24.0
  - setuptools=70.1.1
  - wheel=0.43.0
  - pip:
      - asttokens==2.4.1
      - attribox==0.1.32
      - colorama==0.4.6
      - executing==2.0.1
      - icecream==2.1.3
      - pygments==2.18.0
      - six==1.16.0
      - vistutils==0.1.49
      - pyperclip==1.9.0  # Development only!